# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-25 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('random_list_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randomlist',
            old_name='user',
            new_name='list_name',
        ),
    ]
